apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
spec:
  destination:
    name: ''
    namespace: ''
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://charts.jenkins.io'
    targetRevision: 4.11.1
    chart: jenkins
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
