- name: Main
  hosts: all
  tasks:

    - name: Install Ubuntu packages
      apt:
        name:
          - git
        state: present
      when: ansible_distribution == 'Ubuntu'
      become: true
      become_method: sudo

    - name: Pyenv Git checkout
      ansible.builtin.git:
        repo: 'https://github.com/pyenv/pyenv.git'
        dest:  ~/.pyenv

    - name: Install brew packages
      homebrew:
        name: '{{ item }}'
        state: present
      with_items:
        - python
      when: ansible_distribution == 'MacOSX'

    - name: Install Ubuntu packages
      apt:
        name:
          - python3-dev
          - build-essential
          - libssl-dev
          - zlib1g-dev
          - libbz2-dev
          - libreadline-dev
          - libsqlite3-dev
          - curl
          - libncursesw5-dev
          - xz-utils
          - tk-dev
          - libxml2-dev
          - libxmlsec1-dev
          - libffi-dev
          - liblzma-dev
        state: present
      when: ansible_distribution == 'Ubuntu'
      become: true
      become_method: sudo

    - name: "Add Python to shell config file `~/.ada-learningrc`"
      lineinfile:
        dest: ~/.ada-learningrc
        state: present
        line: "{{ item }}"
        create: true
      with_items:
        - "# TRAIN ansible: python config"
        - "export PYENV_ROOT=~/.pyenv"
        - "export PATH=$PYENV_ROOT/bin:$PATH"
        - "eval \"$(pyenv init -)\""


    - name: Install concrete version for python
      ansible.builtin.shell: "source ~/.ada-learningrc && {{ item }}"
      with_items:
        # speedup pyenv commands
        - cd ~/.pyenv && src/configure && make -C src
        - pyenv --version
        - pyenv install 3.11.7 --skip-existing
        - pyenv global 3.11.7
      args:
        executable: /bin/bash

